import streamlit as st


def render_integrity_checks():
    st.header("2. Experiment Integrity")

    st.markdown(
        """
        Before inference, the raw dataset was validated for experiment integrity.

        The following issues were identified and handled in the pipeline:

        - group / landing-page mismatches were detected and removed
        - duplicate users were detected and reduced to one row per user

        As a result, the final dataset used in this app represents a cleaned, user-level experiment population.
        """
    )

    st.info(
        "Integrity checks and cleaning are performed upstream in the pipeline. "
        "This app uses the cleaned dataset generated by `src/pipeline.py`."
    )